server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/java-2201}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
#  security:
#    user:
#      name: jhon
#      password: jhon

application:
  request-id-header: request-id
  token-expiry-minute: 30
  token-prefix: Bearer
  jwt-secret: dipAnj@L
  auth-header-name: Authorization
  token-validation-regex: ^Bearer\s[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$
  seeder-enabled: true
  api-version: 0.0.1